#pragma once

#include "MirageClient.h"
#include "UpdateNFTExample.generated.h"

/// UUpdateNFTExample provides various functions to get and update NFT's metadata on the blockchain.
UCLASS(Blueprintable, BlueprintType)
class MIRAGESDK_API UUpdateNFTExample : public UMirageClient
{
	GENERATED_UCLASS_BODY()

public:

//#ifndef DOXYGEN_SHOULD_SKIP_THIS	
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere) FString ContractAddress;
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere) FString ABI;
//#endif /* DOXYGEN_SHOULD_SKIP_THIS */

	/// GetNFTInfo function is used to get an NFT's metadata from the blockchain.
	///
	/// The function requires parameters described below and returns nothing.
	/// Inside the function, A POST request is sent to the Mirage API. The request needs a json body containing a device_id, contract_address, abi_hash, method and args. The format is described in the body section below.
	/// string data will be received in json response.
	///
	/// @param abi_hash The hash of the abi string of the contract.
	/// @param tokenId The id of the token hold by the user.
	/// @param Result A callback delegate that will be triggered once a response is received with data.
	/// 
	/// ### Body
	/// ~~~~~~~~~~~~~~~~~~~~~~~.cpp
	/// {"device_id":"YOUR_DEVICE_ID", "contract_address":"0x159D0A933137f3EC155f43834BDFCd534A8bfd61", "abi_hash":"YOUR_ABI_HASH", "method":"getTokenDetails", "args:"YOUR_TOKEN_ID"}
	/// ~~~~~~~~~~~~~~~~~~~~~~~
	UFUNCTION(BlueprintCallable, Category = "MIRAGE SDK")
	void GetNFTInfo(FString abi_hash, int tokenId, FMirageCallCompleteDynamicDelegate Result);

	/// UpdateNFT function is used to update an NFT's metadata on the blockchain and requires the user confirmation through wallet such as metamask.
	///
	/// The function requires parameters described below and returns nothing.
	/// Inside the function, A POST request is sent to the Mirage API. The request needs a json body containing a device_id, contract_address, abi_hash, method and args. The format is described in the body section below.
	/// string data will be received in json response for a "ticket".
	///
	/// @param abi_hash The hash of the abi string of the contract.
	/// @param _tokenId The id of the NFT.
	/// @param _itemType The type of the NFT.
	/// @param _strength The strength of the NFT.
	/// @param _level The level of the NFT.
	/// @param _expireTime The time for the item to expire.
	/// @param Result A callback delegate that will be triggered once a response is received with data.
	/// 
	/// ### Body
	/// ~~~~~~~~~~~~~~~~~~~~~~~.cpp
	/// {"device_id":"YOUR_DEVICE_ID","contract_address":"0x159D0A933137f3EC155f43834BDFCd534A8bfd61","abi_hash":"YOUR_ABI_HASH","method":"updateTokenWithSignedMessage","args":[{"tokenId":YOUR_TOKEN_ID,"itemType":YOUR_ITEM_TYPE,"strength":YOUR_STRENGTH,"level":YOUR_LEVEL,"expireTime":YOUR_EXPIRE_TIME,"signature":""}]}
	/// ~~~~~~~~~~~~~~~~~~~~~~~
	UFUNCTION(BlueprintCallable, Category = "MIRAGE SDK")
	void UpdateNFT(FString abi_hash, int _tokenId, int _itemType, int _strength, int _level, int _expireTime, FMirageCallCompleteDynamicDelegate Result);

	/// GetUpdateNFTResult function is used to get the result of the ticket generated by UpdateNFT(FString, FMirageCallCompleteDynamicDelegate);
	///
	/// The function requires a parameter described below and returns nothing.
	/// Inside the function, A POST request is sent to the Mirage API. The request needs a json body containing a ticket. The format is described in the body section below.
	/// string data will be received in json response for a "data".
	///
	/// @param Result A callback delegate that will be triggered once a response is received with data.
	/// 
	/// ### Body
	/// ~~~~~~~~~~~~~~~~~~~~~~~.cpp
	/// {"ticket":"YOUR_TICKET"}
	/// ~~~~~~~~~~~~~~~~~~~~~~~
	UFUNCTION(BlueprintCallable, Category = "MIRAGE SDK")
	void GetUpdateNFTResult(FString ticketId, FMirageCallCompleteDynamicDelegate Result);
};